in_dir: 'gs://jcosme/clean_data/genomics/data_splits_inverse_1_mer'

out_base_dir: 'gs://jcosme/clean_data/genomics/datasets'

dsplit_file: '/home/jovyan/work/projects/GPU_gene_ETL/configs/make_data_splits_config.yaml'

unq_classes_file: 'gs://jcosme/clean_data/genomics/MarRef_species_unq.parquet' # 

number_of_classes: [1, 2, 4, 8, 16] # the number of classes to randomly select
size_per_class: [500, 1000, 2000, 4000] # the number of training examples to randomly select per class
do_unknown_class: true # default is True
name_for_unknown_class: '_UNKOWN_' # default is _UNKOWN_

rand_seed: 42 # default is 42
do_rand_seed: true # default is true
tgt_col: 'label' # column name of the labels in df
inp_col: 'seq' # column name of the inputs in df

CUDA_VISIBLE_DEVICES: '0'
do_cuda_vis_dev: false
partition_size: '100M' # partition size for dask dataframes. default is '100M'