in_dir: "/home/jovyan/work/projects/COSME/configs/make_data_splits_config.yaml" # absolute path to output destination of parquet or csv file

out_dir: "/media/jcosme/bigdata/COSME/MarRef_species_k_1.parquet" # absolute path to output destination

label_col_name: "label"
input_col_name: "seq"

# add validation to make this 0 - 12
k_mer: 1 # must be an integer in the range 0-12

possible_gene_values: ["A", "C", "G", "T"]
max_seq_len: 150

CUDA_VISIBLE_DEVICES: '0'
do_cuda_vis_dev: false # set to true if you only want to use 1 GPU (set by CUDA_VISIBLE_DEVICES)
partition_size: '100M'