in_file: 'gs://jcosme/raw_data/genomics/MarRef.training.fasta' # absolute path to location of raw .fasta file

out_file: 'gs://jcosme/clean_data/genomics/MarRef_training.parquet' # absolute path to output destination of parquet files (this will be a folder)

# add validation to make this a length = 2 list
# add validation to make sure these three variables make sense
base_col_names: ["seq", "label"]
label_col_name: "label"

fasta_sep: ">" # DO NOT TOUCH THIS

CUDA_VISIBLE_DEVICES: '0'
do_cuda_vis_dev: false # set to true if you only want to use 1 GPU (set by CUDA_VISIBLE_DEVICES)
partition_size: '100M' # partition size for dask dataframes. default is '100M'