in_dir: "/media/jcosme/bigdata/COSME/MarRef_species_k_1.parquet"

in_data_splits_config_file: "/home/jovyan/work/projects/COSME/configs/make_data_splits_config.yaml" # absolute path to output destination of parquet or csv file
out_dir: "/media/jcosme/bigdata/COSME/MarRef_species_k_1.parquet"

unique_classes_data_path: '/media/jcosme/bigdata/MarRef_species_unq_labs.csv' # 

number_of_classes: 16 # the number of classes to randomly select
size_per_class: 8000 # the number of training examples to randomly select per class

rand_seed: 42 # default is 42
do_rand_seed: true # default is true

tgt_col: 'label' # column name of the labels in df
inp_col: 'seq' # column name of the inputs in df

do_unknown_class: true # default is True
name_for_unknown_class: '_UNKOWN_' # default is _UNKOWN_

CUDA_VISIBLE_DEVICES: '0'
do_cuda_vis_dev: false
partition_size: '100M' # partition size for dask dataframes. default is '100M'